services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    # volumes 섹션
    volumes:
      # 1) Windows 호스트 경로 → 컨테이너 경로
      - C:\Users\GFCON\Documents\Project\QdrantMigration\qdrant_storage:/qdrant/storage
    restart: unless-stopped
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      # n8n 보안(기본 인증)
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=<원하는_아이디>
      - N8N_BASIC_AUTH_PASSWORD=<원하는_비밀번호>
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  qdrant_storage:
  n8n_data:
