version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5680:5680"
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5680}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
    volumes:
      - n8n_data:/home/node/.n8n
    
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  n8n_data:
  qdrant_storage: